apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  app_config.py: |
    import os

    # SECURITY SETTINGS
    ALLOWED_HOSTS = ['*']
    SECRET_KEY = os.environ['SECRET_KEY']
    DEBUG = True
    SITE_URL = 'http://statuspage.local'

    # DATABASE SETTINGS (RDS)
    DATABASE = {
        'NAME': 'statuspage',
        'USER': 'statuspage',
        'PASSWORD': os.environ['DB_PASSWORD'], 
        'HOST': 'yifat-avishag-roman-status-page-db.cx248m4we6k7.us-east-1.rds.amazonaws.com',
        'PORT': '5432',
    }

    # REDIS SETTINGS (ElastiCache)
    REDIS = {
        'default': {
            'HOST': 'yifat-avishag-roman-status-page-redis.7fftml.0001.use1.cache.amazonaws.com',
            'PORT': 6379,
            'PASSWORD': '',
            'DATABASE': 0,
            'SSL': False,
        },
        'tasks': {
            'HOST': 'yifat-avishag-roman-status-page-redis.7fftml.0001.use1.cache.amazonaws.com',
            'PORT': 6379,
            'PASSWORD': '',
            'DATABASE': 0,
            'SSL': False,
        },
        'caching': {
            'HOST': 'yifat-avishag-roman-status-page-redis.7fftml.0001.use1.cache.amazonaws.com',
            'PORT': 6379,
            'PASSWORD': '',
            'DATABASE': 1,
            'SSL': False,
        }
    }
