apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "status-page.fullname" . }}-env
  labels:
    app: {{ include "status-page.name" . }}
data:
  DB_HOST: "yifat-avishag-roman-status-page-db.cx248m4we6k7.us-east-1.rds.amazonaws.com"
  DB_USER: "status_admin"
  DB_NAME: "postgres"
  DB_PORT: "5432"
  DB_SSL_MODE: "require"
  REDIS_HOST: "yifat-avishag-roman-status-page-redis.7fftml.0001.use1.cache.amazonaws.com"
