apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "status-page.fullname" . }}
  labels:
    app: {{ include "status-page.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "status-page.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "status-page.name" . }}
    spec:
      containers:
        - name: status-page
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
            - name: STATUS_PAGE_CONFIGURATION
              value: "app_config"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: db-password
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: django-secret-key
          volumeMounts:
            - name: django-config-volume
              mountPath: /app/statuspage/app_config.py
              subPath: app_config.py
          ports:
            - containerPort: 80
      volumes:
        - name: django-config-volume
          configMap:
            name: django-config
