name: Django Status Page CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: status-page-app
  EKS_CLUSTER_NAME: yifat-avishag-roman-status-page-cluster
  # Automatically generate version tags like v1, v2, v3 based on the action run number
  IMAGE_TAG: v${{ github.run_number }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Allows the pipeline to push commits back to the repo

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 1. RUN TERRAFORM FIRST TO CREATE THE INFRASTRUCTURE
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init & Apply
        working-directory: ./infrastructure/terraform
        env:
          TF_VAR_avishag_iam_arn: ${{ secrets.AVISHAG_IAM_ARN }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
        run: |
          terraform init
          terraform apply -auto-approve

      # 2. THEN LOGIN TO ECR (Which Terraform just created/verified)
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 3. BUILD AND PUSH THE IMAGE
      - name: Build, Tag, and Push Docker Image
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.IMAGE_TAG }} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.IMAGE_TAG }}
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.IMAGE_TAG }} $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      # 4. UPDATE HELM VALUES AND COMMIT TO REPO
      - name: Update Helm Chart values.yaml
        run: |
          sed -i "s/tag: .*/tag: \"${{ env.IMAGE_TAG }}\"/" helm/status-page/values.yaml

      - name: Commit and Push Updated Helm Chart
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add helm/status-page/values.yaml
          git commit -m "chore: update image tag to ${{ env.IMAGE_TAG }} [skip ci]" || echo "No changes to commit"
          git push origin main

      # 5. FINALLY, DEPLOY TO EKS VIA HELM
      - name: Update EKS Kubeconfig
        run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME }}

      - name: Deploy to EKS
        run: |
          helm upgrade --install status-page ./helm/status-page --set image.tag=${{ env.IMAGE_TAG }}
